# Generated by Django 4.2.4 on 2023-09-22 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tweet', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='tweet',
            name='shared_with',
            field=models.ManyToManyField(related_name='Tweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
